spring:
  application:
    name: gamyeon-backend
  config:
    import: "optional:consul:"
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true
        format: YAML
        data-key: data
      discovery:
        enabled: true
        service-name: GAMYEON-BACKEND
        instance-id: GAMYEON-BACKEND:${server.port}
        fail-fast: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  server:
    callback-base-url: ${SPRING_SERVER_URL:http://localhost:8080}

ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}




server:
  port: 8080

jwt:
  access-token-expiry: 3600000
  refresh-token-expiry: 604800000
