# src/test/resources/application-test.yml
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    consul:
      enabled: false
      config:
        enabled: false
      discovery:
        enabled: false
